From bda65afcedcbf44efda5f1e5fa430dd672ef5142 Mon Sep 17 00:00:00 2001
From: Matthew Thode <mthode@mthode.org>
Date: Sun, 1 Feb 2015 00:13:59 -0600
Subject: [PATCH 3/3] fixes error logging to use the right exception parent
 class

looks like this was missed

Closes-Bug: #1416798
Change-Id: If68c13b550d665dfa24b7380f53bee7f6fccdb23
---
 neutron/plugins/ml2/plugin.py | 1 -
 1 file changed, 1 deletion(-)

diff --git a/neutron/plugins/ml2/plugin.py b/neutron/plugins/ml2/plugin.py
index a41ffc2..c7c4c4c 100644
--- a/neutron/plugins/ml2/plugin.py
+++ b/neutron/plugins/ml2/plugin.py
@@ -1054,7 +1054,6 @@ class Ml2Plugin(db_base_plugin_v2.NeutronDbPluginV2,
                            one())
             except sa_exc.NoResultFound:
                 return
-            except exc.MultipleResultsFound:
                 LOG.error(_("Multiple ports have port_id starting with %s"),
                           port_id)
                 return
-- 
2.0.5

